### ISSUE TITLE
Could not find proof rule remove_term_formula_axiom

### ISSUE THREAD

**Issue by rodrigo7491** [cvc5/alfc#36]
**Describe the bug**
When running cvc5 in proof-producing mode with the attached .smt2 file (see [test.zip](https://github.com/cvc5/alfc/files/15500175/test.zip)) I get different behaviours for each proof format

1) With `--proof-format=alethe --proof-granularity=theory-rewrite` the output is as below:
```
Fatal failure within virtual cvc5::internal::Node cvc5::internal::proof::AletheNodeConverter::postConvert(cvc5::internal::Node) at /home/runner/work/cvc5/cvc5/src/proof/alethe/alethe_node_converter.cpp:34
Unreachable code reached Fresh Skolems are not allowed

Aborted (core dumped)
```
2) With `--proof-format=alf --proof-granularity=theory-rewrite` a proof is produced successfully but [alfc](https://github.com/cvc5/alfc) rejects the proof with the message below:

```
Error: out.proof_alf:1005.19: Could not find proof rule remove_term_formula_axiom
```
3) With `--proof-format=lfsc --proof-granularity=theory-rewrite` the proof is produced successfully and is validated by the [lfsc checker](https://github.com/cvc5/LFSC) with the message below:
```
success
```

The problem with alethe is probably due to the format not supporting arrays so far (to the best of my knowledge), but according to the [documentation](https://cvc5.github.io/docs/cvc5-1.1.2/proofs/proofs.html) both lfsc and alf should should support arrays. Since the proof was only rejected by alfc it might be a problem with the checker, thus I am opening this issue here rather than on the cvc5 repository.

**cvc5 version/commit**: v1.1.2
**Operating system**: Linux Mint 21.2

**alfc version/commit**: `3c122c02bdb49d239223e683740da59f74816ba7`
**lfsc checker version/commit**: `5a127dbbcf9a0f822768e783dbf892ee90c435d5`
The files required by the checkers were taken from the [cvc5 repository](https://github.com/cvc5/cvc5/tree/main/proofs) (`324a016c8bce89eb9b56d4c62dfab83f29e8f254`).

**Comment by ajreynol** [comment]
Hi @rodrigo7491 , thanks for the issue.

I believe the issue you are running into is using an older version of the cvc5+ALF signature with a newer version of cvc5.

In particular, the name of the rule `remove_term_formula_axiom` was recently changed to `ite_eq` in this commit of cvc5: https://github.com/cvc5/cvc5/commit/c4f5de386f7ac59d866bafe4a191fd986ca77d26.

In general, the best way to be sure you are using the right version of alfc and its signatures with cvc5 is to use the `./contrib/get-alf-checker` script in the cvc5 repository.  Whenever you update cvc5 and you are building from sources, you should run this script as well to ensure the 2 are in sync. This script will give instructions on where it is installed and will include the proper signature file as part of the script.  

Note we also recently simplified our CMake in cvc5 to *not* copy the ALF signatures when installing.  The alfc checker should include the proof signature as-is from the cvc5 repo here: https://github.com/cvc5/cvc5/blob/main/proofs/alf/cvc5/Cvc5.smt3

Let me know if you run into any issues.

Cheers,
Andy

**Comment by rodrigo7491** [comment]
Hi @ajreynol, thanks for the detailed response.

It seems the issue was indeed a mismatch of versions. I've been using the binary of the last release of cvc5 (v1.1.2), but I took the signatures from the main branch of cvc5 and I've been using alfc from its main branch.

Using the `./contrib/get-alf-checker` script from the source code of cvc5 v1.1.2 to get alfc eca2cbd and also using the signatures from there solved the issue. I plan to use the latest release for the time being.

Thanks again,
Rodrigo

**Comment by ajreynol** [comment]
Great to hear.

FYI, in future releases of cvc5, we are planning to establish "stable proof signatures", i.e. the 1.1.3 release of the cvc5+ALF signature, so these issues will be easier to avoid in the future.  I will keep you posted.
